4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
filled_array = np.full((3, 3), 7)  # Example shape 3x3 with fill value 7
print("\nFilled Array (3x3 with 7s):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)
print("\nZeros Like Array (same shape as existing_array):\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(existing_array)
print("\nOnes Like Array (same shape as existing_array):\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n Converted list to Numpy  Array from List:", numpy_array)


Empty Array (2x2):
 [[4.65926878e-310 0.00000000e+000]
 [6.72311926e-310 4.65828413e-310]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3 with 7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array (same shape as existing_array):
 [[0 0]
 [0 0]]

Ones Like Array (same shape as existing_array):
 [[1 1]
 [1 1]]

 Converted list to Numpy  Array from List: [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr_1 = np.arange(10, 50)
print("Array from 10 to 49:", arr_1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr_2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:\n", arr_2)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nMean of random array:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\nMinimum value in 10x10 random array:", min_value)
print("Maximum value in 10x10 random array:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element at index 4
print("\nZero array with 5th element replaced by 1:", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0  # Set the inner values to 0
print("\n2D array with 1 on border and 0 inside:\n", array_2d)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Fill alternating cells with 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array: 0.5180463455296141

Minimum value in 10x10 random array: 0.01360666440865732
Maximum value in 10x10 random array: 0.9637364683382821

Zero array with 5th element replaced by 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = np.add(x, y)
print("Addition of x and y:\n", add_result)

# 2. Subtract the two arrays
subtract_result = np.subtract(x, y)
print("Subtraction of x and y:\n", subtract_result)

# 3. Multiply the array with any integer (multiply by 2)
multiply_x = x * 2
multiply_y = y * 2
print("x multiplied by 2:\n", multiply_x)
print("y multiplied by 2:\n", multiply_y)

# 4. Find the square of each element of the array
square_x = np.square(x)
square_y = np.square(y)
print("Square of elements in x:\n", square_x)
print("Square of elements in y:\n", square_y)

# 5. Find the dot product between v and w, x and v, x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

# 6. Concatenate x and y along rows, and v and w along columns
concat_x_y_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_x_y_row)

concat_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate v and w along columns:\n", concat_v_w_column)

# Using np.vstack and np.hstack
concat_x_y_row_vstack = np.vstack((x, y))
concat_v_w_column_hstack = np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))

print("Concatenate x and y along rows (vstack):\n", concat_x_y_row_vstack)
print("Concatenate v and w along columns (hstack):\n", concat_v_w_column_hstack)

# 7. Try to concatenate x and v
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:\n", concat_x_v)
except Exception as e:
    print("Error while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
y multiplied by 2:
 [[10 12]
 [14 16]]
Square of elements in x:
 [[ 1  4]
 [ 9 25]]
Square of elements in y:
 [[25 36]
 [49 64]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
Concatenate x and y along rows (vstack):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns (hstack):
 [[ 9 11]
 [10 12]]
Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

 For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB !=  BA.
3. Prove (AB)^T=B^T * A^T


.

 Solve the following system of Linear equation using Inverse Methods.

    2x − 3y + z = −1
    x − y + 2z = −3
    3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

 Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = Identity matrix
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A_inv (should be identity matrix):\n", identity_matrix)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("Transpose of AB:\n", AB_T)
print("B^T * A^T:\n", BT_AT)

# 4. Solve the system of linear equations using inverse method
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix
B_eq = np.array([-1, -3, 9])  # Right-hand side matrix

# Calculate the inverse of A
A_inv_eq = np.linalg.inv(A_eq)

# Solve for X: X = A_inv * B
X = np.dot(A_inv_eq, B_eq)
print("Solution to the system of equations (x, y, z):", X)


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [1]:
import time
import numpy as np

# Generate two lists of size 1,000,000 for element-wise operations
size = 1000000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Generate two NumPy arrays of size 1,000,000 for element-wise operations
np_array1 = np.arange(size)
np_array2 = np.arange(size)

# -------------------- 1. Element-wise Addition --------------------

# Using Python Lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
python_list_add_time = time.time() - start_time
print(f"Python List Element-wise Addition Time: {python_list_add_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_sum = np_array1 + np_array2
numpy_add_time = time.time() - start_time
print(f"NumPy Element-wise Addition Time: {numpy_add_time:.6f} seconds")

# -------------------- 2. Element-wise Multiplication --------------------

# Using Python Lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
python_list_mult_time = time.time() - start_time
print(f"Python List Element-wise Multiplication Time: {python_list_mult_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_product = np_array1 * np_array2
numpy_mult_time = time.time() - start_time
print(f"NumPy Element-wise Multiplication Time: {numpy_mult_time:.6f} seconds")

# -------------------- 3. Dot Product --------------------

# Using Python Lists
start_time = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
python_list_dot_time = time.time() - start_time
print(f"Python List Dot Product Time: {python_list_dot_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_dot_product = np.dot(np_array1, np_array2)
numpy_dot_time = time.time() - start_time
print(f"NumPy Dot Product Time: {numpy_dot_time:.6f} seconds")

# -------------------- 4. Matrix Multiplication --------------------

# Create two 1000x1000 matrices
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

# Using Python Lists for Matrix Multiplication
start_time = time.time()
matrix_product_python = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
python_matrix_mult_time = time.time() - start_time
print(f"Python List Matrix Multiplication Time: {python_matrix_mult_time:.6f} seconds")

# Using NumPy Arrays for Matrix Multiplication
np_matrix1 = np.random.rand(1000, 1000)
np_matrix2 = np.random.rand(1000, 1000)

start_time = time.time()
matrix_product_numpy = np.dot(np_matrix1, np_matrix2)
numpy_matrix_mult_time = time.time() - start_time
print(f"NumPy Matrix Multiplication Time: {numpy_matrix_mult_time:.6f} seconds")


Python List Element-wise Addition Time: 0.382345 seconds
NumPy Element-wise Addition Time: 0.015545 seconds
Python List Element-wise Multiplication Time: 0.554043 seconds
NumPy Element-wise Multiplication Time: 0.013963 seconds
Python List Dot Product Time: 0.586601 seconds
NumPy Dot Product Time: 0.002186 seconds
Python List Matrix Multiplication Time: 249.081007 seconds
NumPy Matrix Multiplication Time: 0.071337 seconds
